In [ ]:
# pandas

In [ ]:
import pandas as pd

In [ ]:
# d1  = pd.read_csv("data.csv")

In [ ]:
#create df
d2 = pd.Series([12,5,5,1551,55,111], index =  [1,2,3,4,5,6])

In [ ]:
d2

1      12
2       5
3       5
4    1551
5      55
6     111
dtype: int64

In [ ]:
d3 = pd.Series({1:"ashwani",
                   2:"vansh",
                   3:"kaku"})

In [ ]:
d3

1    ashwani
2      vansh
3       kaku
dtype: object

In [ ]:
# create dataframe
data = {"name":["x","y","z"],
       "age":[19,15,20],
       "gender":["m","f","m"]}
d = pd.DataFrame(data)

In [ ]:
d

  name  age gender
0    x   19      m
1    y   15      f
2    z   20      m

In [ ]:
d.to_csv("df.csv")

In [ ]:

# head, tail, info, describe, shape, columns, dtypes
d.head()

  name  age gender
0    x   19      m
1    y   15      f
2    z   20      m

In [ ]:
d.tail()

  name  age gender
0    x   19      m
1    y   15      f
2    z   20      m

In [ ]:
d.shape

(3, 3)

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   gender  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [ ]:
d.describe()

             age
count   3.000000
mean   18.000000
std     2.645751
min    15.000000
25%    17.000000
50%    19.000000
75%    19.500000
max    20.000000

In [ ]:
d.columns

Index(['name', 'age', 'gender'], dtype='object')

In [ ]:
d.dtypes

name      object
age        int64
gender    object
dtype: object

In [ ]:
# read function take first row of data as an header and if data has no columns name in this case no need of header
# pd.read_csv(".csv", header = None)